### ISSUE TITLE
Crashing in 1.19.1 and 1.19.2

### ISSUE THREAD

**Issue by wati2006** [ByMartrixx/VTDownloader#14]
When I open the VTDownloader GUI the game crashes.
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2022-08-13 13:05:22
Description: Rendering screen

java.lang.NoSuchMethodError: 'void me.bymartrixx.vtd.gui.widget.PackListWidget.method_25311(net.minecraft.class_4587, int, int, int, int, float)'
	at me.bymartrixx.vtd.gui.widget.PackListWidget.method_25394(PackListWidget.java:131)
	at me.bymartrixx.vtd.gui.VTDScreen.method_25394(VTDScreen.java:244)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.bymartrixx.vtd.gui.widget.PackListWidget.method_25394(PackListWidget.java:131)
	at me.bymartrixx.vtd.gui.VTDScreen.method_25394(VTDScreen.java:244)

-- Screen render details --
Details:
	Screen name: me.bymartrixx.vtd.gui.VTDScreen
	Mouse location: Scaled: (249, 235). Absolute: (999.000000, 938.000000)
	Screen size: Scaled: (480, 251). Absolute: (1920, 1001). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2348)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.4, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1124729752 bytes (1072 MiB) / 2906652672 bytes (2772 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: unknown
	Frequency (GHz): 2.71
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5916
	Graphics card #0 versionInfo: DriverVersion=26.20.100.6859
	Graphics card #1 name: NVIDIA GeForce 940MX
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x134d
	Graphics card #1 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 16002.64
	Virtual memory used (MB): 11741.07
	Swap memory total (MB): 3840.00
	Swap memory used (MB): 359.88
	JVM Flags: 3 total; -Xmx6144m -Xms256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		fabric-api: Fabric API 0.59.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.10+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.8+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.16+83a8659290
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.19+9ff28f4090
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.0+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.10+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.6+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.27+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.33+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.2+83a8659290
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.4+bd0a0d4a90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.7+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.29+a6d2f78590
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.17+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.27+9ff28f4090
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.27+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.20+1899036190
			fabric-item-api-v1: Fabric Item API (v1) 1.5.6+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.27+6bee109e90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.19+9ff28f4090
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.17+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+83a8659290
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.5+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.2+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.13+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.16+9ff28f4090
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.3+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.20+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.10+7675279690
			fabric-particles-v1: Fabric Particles (v1) 1.0.9+dc39553a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.23+23c4cfef90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.9+84f79e9d90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.11+5187d39f90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.19+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.13+9ff28f4090
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.6+9ff28f4090
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.21+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.15+9ff28f4090
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.10+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.0+6bee109e90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.25+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.12+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.19+9ff28f4090
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.10+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.2.0+1e232e1390
		fabricloader: Fabric Loader 0.14.9
		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		vt_downloader: VTDownloader 1.0.8+1.19
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce 940MX/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.59, NVIDIA Corporation
	Window size: 1920x1001
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
```

**Comment by arthomnix** [comment]
1.19.1/2 isn't supported yet (see #13)
You can download an unofficial build from that PR from https://github.com/ByMartrixx/VTDownloader/suites/7550358675/artifacts/311595616 (the mod jar is inside the zip file, use the one without `-sources`)

**Comment by wati2006** [comment]
I didn't see that. Thank you!
