### ISSUE TITLE
Download for "Sus sand and gravel" fails

### ISSUE THREAD

**Issue by RhythmicSys** [ByMartrixx/VTDownloader#28]
Trying to download "Sus sand and gravel" pack in 'fun' category fails and causes the loading bar to be stuck on the screen, even after moving to another category.

Error:
```
[15:41:53] [ForkJoinPool.commonPool-worker-3/ERROR]: Pack download failed
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Pack zipping request returned status code 400
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Pack zipping request returned status code 400
	at me.bymartrixx.vtd.VTDMod.lambda$executePackDownload$1(VTDMod.java:168) ~[vt-downloader-2.0.6+1.20.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 4 more
```

### Initially attempting to download the pack
![image](https://github.com/ByMartrixx/VTDownloader/assets/45906780/36f11e32-3d14-4542-b1ba-40c1d3f37294)

### Moving tabs, the loading bar is still stuck and frozen on the screen
![image](https://github.com/ByMartrixx/VTDownloader/assets/45906780/049962ec-30bf-47ab-ab38-0ae4e7929817)

**Comment by IotaBread** [comment]
That's strange... I'll look into it

**Comment by IotaBread** [comment]
It seems the pack isn't even available in the [VanillaTweaks resource packs page](https://vanillatweaks.net/picker/resource-packs/)...

**Comment by IotaBread** [comment]
This pack is marked internally as experimental, and since it isn't shown in the website, I'm guessing that means the pack is in development, so since 2.0.7 it won't be shown in the mod until it's available through regular means
